import type { NextPage } from 'next'
import { useSession } from 'next-auth/react'
import Head from 'next/head'

const Home: NextPage = () => {
  const { data, status } = useSession()
  console.log(data)
  console.log(status)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">Hello!</main>
    </>
  )
}

export default Home
